version: '3.8'

services:
  app:
    build: .
    container_name: assesment_app
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/assesment_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - postgres
    networks:
      - assesment-network

  postgres:
    image: postgres:15-alpine
    container_name: assesment_db
    environment:
      POSTGRES_DB: assesment_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assesment-network

volumes:
  postgres_data:


networks:
  assesment-network:
    driver: bridge
